name: Monthly Dataverse + Bsky

on:
  schedule:
    - cron: "0 6 1 * *"  # At 6 AM UTC on the 1st of every month
  workflow_dispatch:

jobs:
  update-and-post:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.11"

      - name: Install dependencies
        run: |
          pip install requests atproto

      - name: List datasets
        env:
          DATAVERSE_TOKEN: ${{ secrets.DATAVERSE_TOKEN }}
        run: |
          python scripts/dv.py \
            -b https://dataverse.harvard.edu \
            -t $DATAVERSE_TOKEN \
            --alias soodoku \
            -o datasets.json

      - name: Commit updated datasets.json
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          git add datasets.json
          git commit -m "Update datasets.json [skip ci]" || echo "No changes to commit"
          git push

      - name: Post a random dataset to Bsky
        env:
          BSKY_HANDLE: ${{ secrets.BSKY_HANDLE }}
          BSKY_PASSWORD: ${{ secrets.BSKY_PASSWORD }}
        run: python scripts/post-to-bsky.py
